name: port
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  shared_preferences: ^2.3.2
  glitch_text: ^0.1.2
  flutter_gen_runner: ^5.4.0
  build_runner:
  palette_generator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certificates/
    - assets/skills/

flutter_gen:
  output: lib\src\core\assets\
